# Generated by Django 5.2.6 on 2025-09-17 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('reliability', models.FloatField(default=1.0)),
                ('last_hosted', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('excused', 'Excused'), ('absent', 'Absent')], default='present', max_length=10)),
                ('boy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinners.boy')),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('restaurant', models.CharField(blank=True, max_length=120)),
                ('attendees', models.ManyToManyField(related_name='dinners_attended', through='dinners.Attendance', to='dinners.boy')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosted_dinners', to='dinners.boy')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='dinner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinners.dinner'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('dinner', 'boy')},
        ),
    ]
