# Generated by Django 5.2.6 on 2025-09-17 20:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dinner',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddField(
            model_name='dinner',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
