# Generated by Django 5.2.6 on 2025-09-18 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinners', '0002_alter_dinner_options_dinner_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dinner',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.RemoveField(
            model_name='dinner',
            name='created_at',
        ),
        migrations.AddField(
            model_name='boy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='boy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='dinners.boy'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='dinner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='dinners.dinner'),
        ),
    ]
